### ISSUE TITLE
Feature: Add Currently Open File to Task

### ISSUE THREAD

**Issue by matt2930** [kobilee/task-file-organizer#10]
Ideally, there would be some way to quickly add the currently open file to a task. When I click the Add Task option from the menu, it still gives me the file explorer. Maybe another option should be added that is "Add current file to task" or something.

**Comment by kobilee** [comment]
Fix this one when you complained about it yesterday :P 

see the gif in the readme for how to do it

**Comment by matt2930** [comment]
Give me more ways to add it 😆

**Comment by kobilee** [comment]
I gave it to you ❤️
