### ISSUE TITLE
Feature: Change task color

### ISSUE THREAD

**Issue by matt2930** [kobilee/task-file-organizer#11]
I got stuck with bright blue, makes it hard to see the file names. I was unable to change the color of the task.

**Comment by kobilee** [comment]
Yeah going to take a while before I can implement a color picker. Maybe I could give the option to reroll the color, or let the user swap the text to black. what do you think?

**Comment by kobilee** [comment]
I WILL NOT ALLOW YOU TO PICK THE COLOR! THE RANDOMNESS ITS PART OF THE FUN! having said that it will now dynamically swap the color of the text so it is readable :)
